---

- name: "install dependencies"
  become: true
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: "install dependencies 2"
  become: true
  shell:
    cmd: "apt install -y nodejs npm"

- name: "env var"
  become: true
  shell: |
    echo "TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION')}}" >> /home/ubuntu/.env
    echo "TYPEORM_ENTITIES={{ lookup('env', 'TYPEORM_ENTITIES')}}" >> /home/ubuntu/.env
    echo "TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST')}}" >> /home/ubuntu/.env
    echo "TYPEORM_PORT=5432" >> /home/ubuntu/.env
    echo "TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME')}}" >> /home/ubuntu/.env
    echo "TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD')}}" >> /home/ubuntu/.env
    echo "TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE')}}" >> /home/ubuntu/.env
    echo "TYPEORM_MIGRATIONS={{ lookup('env', 'TYPEORM_MIGRATIONS')}}" >> /home/ubuntu/.env
    echo "TYPEORM_MIGRATIONS_DIR={{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}" >> /home/ubuntu/.env

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: "install prometheus"
  become: true
  shell: | 
    # install
    sudo useradd --no-create-home node_exporter
    sudo mkdir /etc/prometheus
    sudo mkdir /var/lib/prometheus
    sudo wget https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    sudo tar xvfz prometheus-2.19.0.linux-amd64.tar.gz
    sudo cp prometheus-2.19.0.linux-amd64/prometheus /usr/local/bin
    sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    sudo cp -r prometheus-2.19.0.linux-amd64/consoles /etc/prometheus
    sudo cp -r prometheus-2.19.0.linux-amd64/console_libraries /etc/prometheus
    sudo cp prometheus-2.19.0.linux-amd64/promtool /usr/local/bin/
    sudo rm -rf prometheus-2.19.0.linux-amd64.tar.gz prometheus-2.19.0.linux-amd64

    sudo touch /etc/prometheus/prometheus.yml
    sudo chmod 777 /etc/prometheus/prometheus.yml
    sudo echo "global:" >> /etc/prometheus/prometheus.yml
    sudo echo "  scrape_interval: 15s" >> /etc/prometheus/prometheus.yml
    sudo echo "  external_labels:" >> /etc/prometheus/prometheus.yml
    sudo echo "    monitor: 'prometheus'" >> /etc/prometheus/prometheus.yml
    sudo echo "scrape_configs:" >> /etc/prometheus/prometheus.yml
    sudo echo "  - job_name: 'prometheus'" >> /etc/prometheus/prometheus.yml
    sudo echo "    static_configs:" >> /etc/prometheus/prometheus.yml
    sudo echo "      - targets: ['localhost:9090']" >> /etc/prometheus/prometheus.yml

    sudo touch /etc/systemd/system/prometheus.service
    sudo chmod 777 /etc/systemd/system/prometheus.service
    sudo echo "[Unit]" >> /etc/systemd/system/prometheus.service
    sudo echo "Description=Prometheus" >> /etc/systemd/system/prometheus.service
    sudo echo "Wants=network-online.target" >> /etc/systemd/system/prometheus.service
    sudo echo "After=network-online.target" >> /etc/systemd/system/prometheus.service
    sudo echo "[Service]" >> /etc/systemd/system/prometheus.service
    sudo echo "User=prometheus" >> /etc/systemd/system/prometheus.service
    sudo echo "Group=prometheus" >> /etc/systemd/system/prometheus.service
    sudo echo "Type=simple" >> /etc/systemd/system/prometheus.service
    sudo echo "ExecStart=/usr/local/bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/var/lib/prometheus --web.console.templates=/etc/prometheus/consoles --web.console.libraries=/etc/prometheus/console_libraries" >> /etc/systemd/system/prometheus.service
    sudo echo "[Install]" >> /etc/systemd/system/prometheus.service
    sudo echo "WantedBy=multi-user.target" >> /etc/systemd/system/prometheus.service

    sudo chown prometheus:prometheus /etc/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/prometheus
    sudo chown prometheus:prometheus /usr/local/bin/promtool
    sudo chown -R prometheus:prometheus /etc/prometheus/consoles
    sudo chown -R prometheus:prometheus /etc/prometheus/console_libraries
    sudo chown -R prometheus:prometheus /var/lib/prometheus

    sudo systemctl daemon-reload
    sudo systemctl start prometheus
    sudo systemctl enable prometheus

- name: "Start Prometheus"
  become: true
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter