---

- name: "install dependencies"
  become: true
  apt:
    name: python3
    state: latest
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    update_cache: yes
    upgrade: yes

- name: "install dependencies 2"
  become: true
  shell:
    cmd: "apt install -y nodejs npm"

- name: "env var"
  become: true
  shell: |
    echo "TYPEORM_CONNECTION={{ lookup('env', 'TYPEORM_CONNECTION')}}" >> /home/ubuntu/.env
    echo "TYPEORM_ENTITIES={{ lookup('env', 'TYPEORM_ENTITIES')}}" >> /home/ubuntu/.env
    echo "TYPEORM_HOST={{ lookup('env', 'TYPEORM_HOST')}}" >> /home/ubuntu/.env
    echo "TYPEORM_PORT=5432" >> /home/ubuntu/.env
    echo "TYPEORM_USERNAME={{ lookup('env', 'TYPEORM_USERNAME')}}" >> /home/ubuntu/.env
    echo "TYPEORM_PASSWORD={{ lookup('env', 'TYPEORM_PASSWORD')}}" >> /home/ubuntu/.env
    echo "TYPEORM_DATABASE={{ lookup('env', 'TYPEORM_DATABASE')}}" >> /home/ubuntu/.env
    echo "TYPEORM_MIGRATIONS={{ lookup('env', 'TYPEORM_MIGRATIONS')}}" >> /home/ubuntu/.env
    echo "TYPEORM_MIGRATIONS_DIR={{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}" >> /home/ubuntu/.env

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present


- name: "install prometheus"
  become: true
  shell: | 
    # install
    useradd --no-create-home node_exporter
    wget https://github.com/prometheus/node_exporter/releases/download/v1.0.1/node_exporter-1.0.1.linux-amd64.tar.gz
    tar xzf node_exporter-1.0.1.linux-amd64.tar.gz 
    cp node_exporter-1.0.1.linux-amd64/node_exporter /usr/local/bin/node_exporter
    rm -rf node_exporter-1.0.1.linux-amd64.tar.gz node_exporter-1.0.1.linux-amd64

- name: "Copy Prometheus node-exporter-config to server"
  become: true
  copy: 
    src: files/node-exporter.service
    dest: /etc/systemd/system/

- name: "Start Prometheus"
  become: true
  shell: |
    systemctl daemon-reload
    systemctl enable node-exporter
    systemctl start node-exporter
    systemctl status node-exporter